### ISSUE TITLE
Getting error on react native 0.57

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [openGeeksLab/react-native-fluid-slider#2]
Getting error on React native 0.57

![screenshot_20181003-130519](https://user-images.githubusercontent.com/22089729/46390958-1e339780-c70d-11e8-9dde-16bff4837f0a.png)

**Comment by openGeeksLab** [comment]
@ManigandanRaamanathan there is was the incorrect usage example. Use `import Slider from 'react-native-fluid-slider';` instead of `import Slider from '@opengeekslab/react-native-fluid-slider';`
